---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: demo

data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: demo
  DB_USER: demo_user
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: demo

type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: superrootpwd   # change this in production
  DB_PASSWORD: demopwd                # demo_user password
